### ISSUE TITLE
Write a Java program to create a package which has classes and methods to read Student Admission details.

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Java-hacktoberfest23#10]

**Comment by kushal-lalwani** [comment]
Can i please get this issue assigned for my first PR in HacktoberFest.

**Comment by rajiv57** [comment]
can you please assign this issue to me

**Comment by kushal-lalwani** [comment]
> Can i please get this issue assigned for my first PR in HacktoberFest.

Please Check my PR , Suggest any changes. #18
