### ISSUE TITLE
Terminal/console based project on Task Manager and Remainder System.

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Java-hacktoberfest23#101]
This project should completely run in terminal and should be purely programmed with Java. 

Your program needs to solve two important needs of this project, they are:

- [ ] Task Manager: The program should take input from the user to create tasks, view tasks, mark task as completed and exit.
- [ ] Task Remainder: Should contain remainder system. When a task doesn't get completed it should display "Task is due!" without any actions done by the user.

You can customize your project in whichever way you want. Don't forget to solve the two important needs. 

Thank You.

**Comment by abhinavs1920** [comment]
Please assign this issue to me. I want to work on it
