### ISSUE TITLE
Solve Question 1

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Java-hacktoberfest23#19]
Create a class called Calculator which has different add methods. Overload the methods such that the parameters can be of the following pattern.

a) Both are of int data type.
b) Both are of double data type.
c) First parameter is of int data type and second parameter is of double data type.
d)First parameter is of double data type and second parameter is of int data type

Create a separate class for implementation of above methods.

**Comment by sotiriszogos** [comment]
Hello, could you please assign it to me?
