### ISSUE TITLE
Merge sort in Java

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Java-hacktoberfest23#2]

**Comment by AdityaDhavale** [comment]
@chetannihith I would like to work on this issue , will u please assign me?

**Comment by chetannihith** [comment]
Assigned!!

**Comment by tanay-nagde** [comment]
@chetannihith could you please assign me this

**Comment by gulatikeshav** [comment]
@chetannihith  please assign me this issue

**Comment by AKG1301** [comment]
@chetannihith , i would like to work on it

**Comment by AdityaDhavale** [comment]
@chetannihith It doesn't show that I've been assigned

**Comment by AdityaDhavale** [comment]
Hey @chetannihith I've added the code for merge sort in Java . Please check and kindly merge my PR

**Comment by SachinChougule10** [comment]
Hello, I will like to work on this issue.
