### ISSUE TITLE
Solve Question 2

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Java-hacktoberfest23#20]
Write a class Account which should have a private instance variable called balance. Create gettter and setter methods for balance variable. Also write two methods
with the following signature –
void deposit(int amt)
void withdraw(int amt)

withdraw method should give a message insufficient amount if the amount you are trying to withdraw is more than current balance otherwise balance need to be reduced
by the amount withdrawn.

Create another class TestAccount and write down main method there. Create an object of Account class. Start the account with Rs 2000. Add Rs 500 and withdraw Rs 1800. Then show the balance.

**Comment by spideyWebb** [comment]
Hii chetannihith . Please assign me this issue. I am good at Java Programming.
