### ISSUE TITLE
Solve Question 3.1

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Java-hacktoberfest23#21]
Create a class named 'School' with the following data members

1 –Roll no of Student
2 –Name of Student
3 - Address
4 -Branch
5- Marks in 4 subjects
6- Percentage

7- Grade

Class 'School' has a method for the following

Generate a unique rollno for each student. For first Student, roll number will be ABC1012019, for second student it will be ABC1022019 and so on.

**Comment by Milind-Palaria** [comment]
@chetannihith could you assign this to me?

**Comment by gopalkrishna2004** [comment]
@chetannihith  plz assign this to me.
