### ISSUE TITLE
Solve Question 3.5

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Java-hacktoberfest23#36]
Create a class named 'School' with the following data members

1 –Roll no of Student
2 –Name of Student
3 - Address
4 -Branch
5- Marks in 4 subjects
6- Percentage

7- Grade

Class 'School' has a method for the following

The program will support the following menu based activities: do the following operations:
Number of students are to be entered by user. Depending upon the number of students, enter the information (name, address, type of account, balance) for each student.

Q. Remove a particular student who has left the school and display the information of rest of the students

**Comment by AdityaDhavale** [comment]
@chetannihith I would like to work on this issue , will u please assign me?

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by hydraveer** [comment]
can i work on this?

**Comment by siddhant2002** [comment]
Hi @hydraveer , currently I'm working on this issue.

**Comment by siddhant2002** [comment]
Raised pr #77 . Please review @chetannihith . Thanks.

**Comment by Archita13Mystic** [comment]
Could you please assign this issue to me @chetannihith

**Comment by aditya-mistri** [comment]
Please assign me this issue @chetannihith

**Comment by akshita1420** [comment]
Please assign me this issue @chetannihith

**Comment by Sajjad01-chaus** [comment]
i can solve it can you assign me this issue please

**Comment by Tanishaclippy** [comment]
Can I solve this ??
