### ISSUE TITLE
Constructor Overloading

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Java-hacktoberfest23#39]
Create a class to print the area of a square and a rectangle. Use methods to assign the values and print the details. Implement the program using a constructor for initializing the values. (Use constructor overloading)

**Comment by mayankch283** [comment]
Hi. I can do this one. Kindly /assign

**Comment by kushal-lalwani** [comment]
Hey, Can i please get this assigned. Ready to contribute.
