### ISSUE TITLE
bubble sort in java 

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Java-hacktoberfest23#6]

**Comment by AdriaGual** [comment]
Hey there!

I've gone ahead and created a pull request for this issue: [12](https://github.com/chetannihith/Java-hack/pull/12)

Would it be possible to assign this issue to me?

Thanks a bunch!

**Comment by chetannihith** [comment]
Assigned!
Welcome.

**Comment by aryankshl** [comment]
hey @chetannihith can you assign this to me?

**Comment by SachinChougule10** [comment]
Hello, I would like to work on this issue.
