### ISSUE TITLE
Add two numbers in Java using command line arguments

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Java-hacktoberfest23#7]

**Comment by sidhartha2002** [comment]
**Hey Bro, plz assign me the task so that I will start working on it.
Thanks.**

**Comment by aryankshl** [comment]
Hey @chetannihith can you assign this to me?

**Comment by AdityaDhavale** [comment]
Hey @chetannihith I would like to work on this issue , will u please assign me?
