### ISSUE TITLE
Repository Structuring in proper format

### ISSUE THREAD

**Issue by aayush105** [chetannihith/Java-hacktoberfest23#76]
This issue is raised to address the formatting and code structure concerns within the repository. The current organization of files and code is not following best practices, which can make it challenging for contributors and users to navigate and utilize the content effectively.

To improve the repository, we should consider the following actions:

1) Define Clear Structure: We need to define a clear and consistent structure for the repository. This includes organizing code according to the programming language.

2) Standardize File and Folder Names: Standardize the naming conventions for files and folders to make them more descriptive and easier to understand.

3) Remove Unnecessary Files: Identify and remove irrelevant files like .DS_Store and .gitgnore. Keep the repository clean and free from clutter.

By addressing these issues, we can enhance the overall quality and usability of the repository. Please feel free to share your thoughts and suggestions on how we can achieve these improvements effectively. Your input is valuable in making this repository more accessible and user-friendly for all.

**Comment by aayush105** [comment]
@chetannihith please review this issue and assign this to me.

**Comment by akshita1420** [comment]
@chetannihith please review this issue and assign this to me

**Comment by aayush105** [comment]
> @chetannihith please review this issue and assign this to me
> 

Its already done by me, and assigned to me.
And stop copying the message @akshita1420
