### ISSUE TITLE
Add CONTRIBUTING.md file 

### ISSUE THREAD

**Issue by aayush105** [chetannihith/Java-hacktoberfest23#81]
This files describe how to fork , clone, create branch, commit message, and push to the repository which is followed inorder to get their PRs merged.

**Comment by aayush105** [comment]
@chetannihith please assign this to me.

**Comment by ghost** [comment]
@aayush105 please assign me this issue i am just new to open source and recently watched all the tutorials so thats why i can do this and start my open source journey.

**Comment by aayush105** [comment]
> @aayush105 please assign me this issue i am just new to open source and recently watched all the tutorials so thats why i can do this and start my open source journey.

Sorry brother you can contribute in other repository for the same files.
Thank you @pravin-singh-parihar
